### ISSUE TITLE
Thread safe?

### ISSUE THREAD

**Issue by ghost** [swstephe/py2jdbc#1]
Hello,

I was wondering can this be used safely with multi-threading?
I've tried using JayDeBeAPI in a multithreaded scenario but it seems like JPype1 produces a seg-fault.

Thanks!

**Comment by swstephe** [comment]
Sorry, I didn't see this until now.  I've designed it to be as multi-threaded as Python will allow.  Each connection and cursor maintains their own mapping to a JNI environment, which is all under the JNI global environment, so you shouldn't seg fault.  I believe JPype pipes through external java processes, while I'm calling JNI from the same process.  However, I wouldn't say it is 100% threadsafe since access to objects might not be atomic and there is no use of a locking mechanism.  I'm also not sure if calls to JNI/JDBC would block.

**Comment by swstephe** [comment]
Answered question.
